# Generated by Django 3.1 on 2020-08-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20)),
                ('dates', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=50)),
                ('band', models.CharField(max_length=50)),
            ],
        ),
    ]
